import type {
  EventQuery,
  ExperimentQuery,
  LedgerQuery,
  MemoryQuery,
  TaskQuery,
} from "@/lib/contracts/types";

export const qk = {
  session: ["session"] as const,
  sources: ["sources"] as const,
  source: (id: string) => ["sources", id] as const,
  ingestion: (sourceId?: string) => ["ingestion", sourceId ?? "all"] as const,
  overview: (sourceId: string) => ["overview", sourceId] as const,
  media: (sourceId: string) => ["media", sourceId] as const,
  detections: (sourceId: string) => ["detections", sourceId] as const,
  map: (sourceId: string) => ["map", sourceId] as const,
  pose: (sourceId: string) => ["pose", sourceId] as const,
  lidar: (sourceId: string) => ["lidar", sourceId] as const,
  events: (query: EventQuery) => ["events", query] as const,
  event: (id: string) => ["event", id] as const,
  objects: (sourceId: string) => ["objects", sourceId] as const,
  object: (id: string) => ["object", id] as const,
  transitions: (objectId: string) => ["transitions", objectId] as const,
  intervals: (objectId: string) => ["intervals", objectId] as const,
  questions: (sourceId: string) => ["questions", sourceId] as const,
  question: (id: string) => ["question", id] as const,
  evidence: (id: string) => ["evidence", id] as const,
  memory: (query: MemoryQuery) => ["memory", query] as const,
  memoryItem: (id: string) => ["memory-item", id] as const,
  memoryHistory: (id: string) => ["memory-history", id] as const,
  runtime: (sourceId: string) => ["runtime", sourceId] as const,
  ledger: (query: LedgerQuery) => ["ledger", query] as const,
  series: (sourceId: string, runId?: string) => ["series", sourceId, runId ?? "active"] as const,
  tasks: (query: TaskQuery) => ["tasks", query] as const,
  task: (id: string) => ["task", id] as const,
  experiments: (query?: ExperimentQuery) => ["experiments", query ?? {}] as const,
  experiment: (id: string) => ["experiment", id] as const,
  experimentSeries: (id: string) => ["experiment-series", id] as const,
  experimentLedger: (id: string) => ["experiment-ledger", id] as const,
  manifest: (id: string) => ["manifest", id] as const,
  reports: ["reports"] as const,
  report: (id: string) => ["report", id] as const,
};
